version: '3.4'

services:
  db:
    image: mysql:8.0.13
    command: 
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
    restart: always
    environment:
      MYSQL_ROOT_HOST: %
      MYSQL_ROOT_PASSWORD: 123456
    ports:
       - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: .
      dockerfile: src/Server/IdentityServer/Dockerfile

  javascriptclient:
    image: ${DOCKER_REGISTRY-}javascriptclient
    build:
      context: .
      dockerfile: src/Client/JavaScriptClient/Dockerfile